// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jo5h-RomK94sMIKubxH3iDnI_o99vfs',
    appId: '1:498232406001:web:bdedec096a2d54a2179e50',
    messagingSenderId: '498232406001',
    projectId: 'playsphere-4618e',
    authDomain: 'playsphere-4618e.firebaseapp.com',
    storageBucket: 'playsphere-4618e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7jo5h-RomK94sMIKubxH3iDnI_o99vfs',
    appId: '1:498232406001:android:your_android_app_id',
    messagingSenderId: '498232406001',
    projectId: 'playsphere-4618e',
    storageBucket: 'playsphere-4618e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jo5h-RomK94sMIKubxH3iDnI_o99vfs',
    appId: '1:498232406001:ios:your_ios_app_id',
    messagingSenderId: '498232406001',
    projectId: 'playsphere-4618e',
    storageBucket: 'playsphere-4618e.firebasestorage.app',
    iosBundleId: 'com.example.playConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jo5h-RomK94sMIKubxH3iDnI_o99vfs',
    appId: '1:498232406001:ios:your_ios_app_id',
    messagingSenderId: '498232406001',
    projectId: 'playsphere-4618e',
    storageBucket: 'playsphere-4618e.firebasestorage.app',
    iosBundleId: 'com.example.playConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7jo5h-RomK94sMIKubxH3iDnI_o99vfs',
    appId: '1:498232406001:web:bdedec096a2d54a2179e50',
    messagingSenderId: '498232406001',
    projectId: 'playsphere-4618e',
    authDomain: 'playsphere-4618e.firebaseapp.com',
    storageBucket: 'playsphere-4618e.firebasestorage.app',
  );
}
